### ISSUE TITLE
Unable to update profile picture

### ISSUE THREAD

**Issue by Eduardo06sp** [egemen-github/odinbar#1]
Console error shown: `Error: Form responses must redirect to another location`
Going back and refreshing, it still show my old, default profile picture.

Tested in Linux Firefox (Developer) v103
and ChromeOS Chrome v103.

**Comment by egemen-dev** [comment]
Thank you for letting me know about it. 

 It was because if you are signed up with google, you don't have a current password to enter when editing the user. So I used devise's `update_without_password` method to be able to update or edit user. https://github.com/egemen-github/odinbar/commit/8b5e9792ab3d4360947a052296555f5c2ecfccef
 
 Fixed now 👍
